# Generated by Django 3.1.7 on 2021-02-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrise_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
