# Generated by Django 3.1.7 on 2021-02-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrise_app', '0002_auto_20210223_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='lastest_logout',
            new_name='logout_at',
        ),
    ]
